vich_uploader:
    db_driver: orm

    mappings:
        evenement:
            uri_prefix: /imgs/evenement
            upload_destination: '%kernel.project_dir%/public/imgs/evenement'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
